name: device_apps_example
description: Demonstrates how to use the device_apps plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  device_apps:
    path: ../

flutter:
  uses-material-design: true

environment:
  flutter: ^3.24.4
  sdk: ^3.5.0